version: '3.5'

services:

  ng-calc:
    container_name: ng-calc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5001:4200'